export const SAMPLE_REQUESTS = [
  {
    id: 'FB-9812A',
    contactName: 'Saba Tekle',
    contactPhone: '+251 911 123 456',
    eventType: 'Anniversary',
    guestCount: 85,
    eventDate: new Date(Date.now() + 86400000 * 45).toISOString(),
    designStyle: 'Three-tier custom cream cake decorated with fresh golden-trimmed roses.',
    flavor: 'Madagascar Vanilla Bean',
    tierCount: 3,
    specialInstructions: 'Safe wrapping for travel. Pickup will occur at pre-scheduled slot.',
    requestDate: 'June 18, 2026',
    status: 'Designing',
    price: 11500,
  },
  {
    id: 'FB-9231B',
    contactName: 'Kidus Solomon',
    contactPhone: '+251 912 345 678',
    eventType: 'Birthday',
    guestCount: 25,
    eventDate: new Date(Date.now() + 86400000 * 12).toISOString(),
    designStyle: 'Clean modern custom iced birthday layout with golden edges.',
    flavor: 'Rich Chocolate Ganache',
    tierCount: 1,
    specialInstructions: 'Minimalist chocolate wording directly on cake surface.',
    requestDate: 'June 19, 2026',
    status: 'Priced',
    price: 2800,
  },
  {
    id: 'FB-8831C',
    contactName: 'Almaz Belay',
    contactPhone: '+251 922 987 654',
    eventType: 'Wedding',
    guestCount: 150,
    eventDate: new Date(Date.now() + 86400000 * 60).toISOString(),
    designStyle: 'Four-tier traditional Ethiopian wedding layout with cascaded sugar jasmine flowers.',
    flavor: 'Red Velvet with Cream Cheese',
    tierCount: 4,
    specialInstructions: 'Timely refrigerated handoff is highly critical.',
    requestDate: 'June 20, 2026',
    status: 'Confirmed',
    price: 18500,
    finalPrice: 18500,
  }
];