export const SAMPLE_REVIEWS = [
  {
    id: 'rev-seed-01',
    rating: 5,
    content: "Yodit created the most stunning three-tier cake for our 25th anniversary. The gold-trimmed roses were absolutely breathtaking. Every guest asked where we got it!",
    author: 'Saba Tekle',
    eventType: 'Anniversary',
    role: 'Host',
    date: 'March 15, 2026',
  },
  {
    id: 'rev-seed-02',
    rating: 5,
    content: "Ordered a birthday cake for my wife and it exceeded every expectation. The Madagascar vanilla was divine and the presentation was museum-worthy.",
    author: 'Kidus Solomon',
    eventType: 'Birthday',
    role: 'Host',
    date: 'February 20, 2026',
  },
  {
    id: 'rev-seed-03',
    rating: 5,
    content: "Our wedding cake was the centerpiece of the reception. Four tiers of perfection with cascading sugar jasmine flowers. Yodit understood our vision perfectly.",
    author: 'Almaz Belay',
    eventType: 'Wedding',
    role: 'Host',
    date: 'January 10, 2026',
  },
  {
    id: 'rev-seed-04',
    rating: 5,
    content: "We commissioned Flavour Bites for our company milestone celebration. The custom branding on the cake was flawless, and the red velvet was the best I have ever tasted.",
    author: 'Bereket Hailu',
    eventType: 'Corporate',
    role: 'Host',
    date: 'April 5, 2026',
  },
  {
    id: 'rev-seed-05',
    rating: 5,
    content: "Yodit made a magical fairytale cake for my daughter's 7th birthday. The marzipan animals were so cute the kids could barely eat them! Thank you for making her day so special.",
    author: 'Meron Tadesse',
    eventType: 'Birthday',
    role: 'Host',
    date: 'May 12, 2026',
  },
];